name: my first ci/cd setup for springboot
on:
  push:
    branches:
      - paresh-feb25-practice-01
  pull_request:
    branches:
      - paresh-feb25-practice-01
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Setup SSH key
        run: |
          echo "${{secrets.EC2_SSH_KEY_FIRST_PEM}}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          # Upload JAR
          scp -o StrictHostKeyChecking=no -i private_key.pem ./target/demo-0.0.2-SNAPSHOT.jar ${{secrets.EC2_USER_FIRST_APP}}@${{secrets.EC2_HOST_FIRST_APP}}:~/
          # Restart the app (kill existing process and start new one)
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            pkill -f 'java -jar' || true  # Kill existing Java process, ignore if none
            nohup java -jar ~/my-app.jar &
          EOF